### PR TITLE
Fix New Relic integration tests.

### PR DESCRIPTION
**Pull request by a-feld**
@vastin This PR supersedes https://github.com/aws-observability/aws-otel-test-framework/pull/240

Can you try testing with this?

### CODE REVIEW

**Comment by vastin** [comment]
@a-feld OK. I will run test with this PR.

**Comment by vastin** [comment]
@a-feld I tested this PR with https://github.com/aws-observability/aws-otel-collector/pull/392 and it passed mock test.

**Comment by mxiamxia** [comment]
I have concern that `/*` is too wild that could mistake the other requests as valid data push request and have the invalid tests passed. Can we add `/metric/v1/` and `/trace/v1` in mock server as validation path and keep `/putdata*`?

**Comment by a-feld** [comment]
Done! 😄

**Review by vastin — APPROVED** [review]

**Comment by mxiamxia** [comment]
Thanks!

**Pull request merged**
