### PR TITLE
Add otlp_logs test case

### PR DESCRIPTION
**Pull request by vasireddy99**
**Description:**
Add `otlp_logs` test case in the batch generator

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bryan-aguilar — COMMENTED** [review]
Why is this necessary? this is just mock test data.

**Comment by vasireddy99** [comment]
> Why is this necessary? this is just mock test data.

Do we any changes in the batch processor, other than this change here - https://github.com/aws-observability/aws-otel-collector/pull/2448

**Comment by bryan-aguilar** [comment]
> > Why is this necessary? this is just mock test data.
> 
> Do we any changes in the batch processor, other than this change here - [aws-observability/aws-otel-collector#2448](https://github.com/aws-observability/aws-otel-collector/pull/2448)

no

**Comment by vasireddy99** [comment]
Thanks Bryan, closing this PR, not required.

**Pull request closed without merging**
