### PR TITLE
Upgrade Log4j (#439)

### PR DESCRIPTION
**Pull request by sethAmazon**
https://github.com/aws-observability/aws-otel-test-framework/issues/439

### CODE REVIEW

**Comment by aateeqi** [comment]
What testing has been done for this?

**Comment by sethAmazon** [comment]
Just gradle build. Upgrading the logging fw should not affect much

**Comment by sethAmazon** [comment]
./gradlew :load-generator:run --args="trace -r=100 -u=localhost:4317 -d=otlp"
Screen Shot 2021-12-16 at 10 50 33 AM

**Comment by sethAmazon** [comment]
terraform apply -auto-approve -var-file="../testcases/otlp_metric/parameters.tfvars" -var="aoc_image_repo=public.ecr.aws/aws-observability/aws-otel-collector" -var="testcase=../testcases/otlp_metric" -var="aoc_version=v0.15.0"
Screen Shot 2021-12-16 at 10 56 49 AM

**Review by jefchien — APPROVED** [review]

**Review by khanhntd — APPROVED** [review]
LGTM

**Pull request merged**
